version: "3.8"

services:
  bitwarden:
    image: ghcr.io/bitwarden/self-host:beta
    container_name: bitwarden
    restart: unless-stopped
    ports:
      - "8080:8080"

  db:
    image: mariadb:10
    container_name: db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    restart: unless-stopped

# volumes:
#   bitwarden:
#   db-data: