version: "3.8"

services:
  bitwarden:
    image: ghcr.io/bitwarden/self-host:beta
    container_name: bitwarden
    restart: unless-stopped
    ports:
      - "8080:8080"

# volumes:
#   bitwarden:
#   db-data: