version: "3.8"

services:
  bitwarden:
    image: ghcr.io/bitwarden/self-host:beta
    container_name: bitwarden
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - bitwarden:/etc/bitwarden

  db:
    image: mariadb:10
    container_name: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql

volumes:
  bitwarden:
  data: