services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      NTFY_BASE_URL: http://ntfy.bmoore.local
      NTFY_BEHIND_PROXY: "true"
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - ./etc:/etc/ntfy
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --tries=1 http://127.0.0.1/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped