services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: host
    ports:
      - "192.168.86.208:53:53/tcp"
      - "192.168.86.208:53:53/udp"
    #   - "67:67/udp"
    #   - "8070:80/tcp"
    #   - "8073:443/tcp"
    environment:
      TZ: 'America/Indianapolis'
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.bmoore.local
      VIRTUAL_PORT: 80
      WEBPASSWORD: #'TEMP_PASSWORD' #'set a secure password here or it will be random'
      WEBPASSWORD_FILE: './etc-pihole/adminpw.txt'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)    
    restart: unless-stopped