## traefik.yml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Docker configuration backend
providers:
  docker:
    exposedByDefault: true
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
  file:
    directory: /etc/traefik
    watch: true

log:
  level: DEBUG
  filepath: /var/log/traefik/traefik.log

accesslog:
  format: common
  filePath: /var/log/traefik/access.log

# API and dashboard configuration
api:
  dashboard: true
  disableDashboardAd: true
  insecure: true

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  stage:
    acme:
      email: bmoore@bmoore.tech
      storage: /certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        provider: cloudflare
        entryPoint: web
        delayBeforeCheck: 10
  prod:
    acme:
      email: bmoore@bmoore.tech
      storage: /certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        provider: cloudflare
        entryPoint: web
        delayBeforeCheck: 10
