services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian
    restart: unless-stopped
    # ports:
    #   - 8080:8080 # Obsidian Web Interface
    #   #- 27123:27123 # Local REST API Plugin HTTP Server Port
    #   #- 27124:27124 # Local REST API Plugin HTTPS Server Port
    # expose:
    #   - 8080
    #   - 27123
    #   - 27124
    volumes:
      - ./vaults:/vaults # The location on the host for your Obsidian Vaults
      - ./config:/config # The location to store Obsidan configuration and ssh data for obsidian-git
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Ameria/Indianapolis
      - DOCKER_MODS=linuxserver/mods:universal-git # Use to add mods to the container like git.
      - KEYBOARD=en-us-qwerty # Used to se the keyboard being used for input. E.g. KEYBOARD=en-us-qwerty or KEYBOARD=de-de-qwertz